import { z } from "zod"

// Comprehensive list of valid TLDs to reduce backend load
const VALID_TLDS = [
  // Generic TLDs
  "com",
  "org",
  "net",
  "edu",
  "gov",
  "mil",
  "int",
  "info",
  "biz",
  "name",
  "pro",
  "museum",
  "coop",
  "aero",
  "jobs",
  "mobi",
  "travel",
  "tel",
  "cat",
  "asia",
  "post",
  "xxx",
  "arpa",

  // New generic TLDs (most popular ones)
  "app",
  "dev",
  "tech",
  "io",
  "ai",
  "co",
  "me",
  "tv",
  "cc",
  "ly",
  "be",
  "it",
  "us",
  "uk",
  "ca",
  "de",
  "fr",
  "jp",
  "au",
  "in",
  "br",
  "mx",
  "ru",
  "cn",
  "kr",
  "sg",
  "hk",
  "tw",
  "th",
  "my",
  "id",
  "ph",
  "vn",

  // Business and professional
  "business",
  "company",
  "corp",
  "inc",
  "llc",
  "ltd",
  "agency",
  "consulting",
  "services",
  "solutions",
  "group",
  "partners",
  "associates",
  "enterprises",
  "industries",
  "holdings",
  "ventures",
  "capital",
  "investments",
  "finance",
  "bank",
  "insurance",
  "legal",
  "law",
  "attorney",
  "accountant",
  "tax",
  "audit",
  "marketing",
  "advertising",
  "media",
  "design",
  "studio",
  "creative",
  "digital",
  "online",
  "web",
  "website",
  "blog",
  "news",
  "press",
  "magazine",
  "publishing",
  "books",
  "education",
  "school",
  "university",
  "college",
  "academy",
  "training",
  "courses",
  "learning",
  "study",
  "research",
  "science",
  "technology",
  "software",
  "systems",
  "network",
  "cloud",
  "hosting",
  "server",
  "data",
  "analytics",
  "security",
  "cyber",
  "protection",
  "safety",
  "health",
  "medical",
  "doctor",
  "clinic",
  "hospital",
  "pharmacy",
  "dental",
  "care",
  "wellness",
  "fitness",
  "gym",
  "sports",
  "games",
  "entertainment",
  "music",
  "video",
  "photo",
  "art",
  "gallery",
  "museum",
  "culture",
  "events",
  "party",
  "wedding",
  "travel",
  "hotel",
  "restaurant",
  "food",
  "cafe",
  "bar",
  "shop",
  "store",
  "market",
  "sale",
  "buy",
  "trade",
  "exchange",
  "auction",
  "deals",
  "discount",
  "coupon",
  "gift",
  "fashion",
  "style",
  "beauty",
  "jewelry",
  "watches",
  "luxury",
  "premium",
  "vip",
  "club",
  "member",
  "community",
  "social",
  "network",
  "forum",
  "chat",
  "email",
  "mobile",
  "phone",
  "call",
  "sms",
  "message",
  "communication",
  "connect",
  "link",
  "share",
  "like",
  "love",
  "life",
  "live",
  "world",
  "global",
  "international",
  "local",
  "city",
  "town",
  "place",
  "location",
  "map",
  "guide",
  "directory",
  "list",
  "search",
  "find",
  "get",
  "go",
  "do",
  "make",
  "build",
  "create",
  "new",
  "best",
  "top",
  "first",
  "last",
  "next",
  "now",
  "today",
  "tomorrow",
  "future",
  "past",
  "time",
  "date",
  "year",
  "month",
  "week",
  "day",
  "hour",
  "minute",
  "second",
  "fast",
  "quick",
  "easy",
  "simple",
  "free",
  "cheap",
  "low",
  "high",
  "big",
  "small",
  "mini",
  "micro",
  "nano",
  "mega",
  "super",
  "ultra",
  "max",
  "plus",
  "pro",
  "expert",
  "master",
  "guru",
  "ninja",
  "hero",
  "star",
  "king",
  "queen",
  "prince",
  "princess",
  "lord",
  "lady",
  "sir",
  "miss",
  "mr",
  "mrs",
  "dr",
  "prof",
  "ceo",
  "cto",
  "cfo",
  "cmo",
  "vp",
  "director",
  "manager",
  "lead",
  "senior",
  "junior",
  "intern",
  "student",
  "teacher",
  "coach",
  "mentor",
  "advisor",
  "consultant",
  "specialist",
  "expert",
  "professional",
  "certified",
  "licensed",
  "registered",
  "official",
  "authorized",
  "approved",
  "verified",
  "trusted",
  "secure",
  "safe",
  "reliable",
  "quality",
  "premium",
  "standard",
  "basic",
  "advanced",
  "custom",
  "personal",
  "private",
  "public",
  "open",
  "closed",
  "limited",
  "unlimited",
  "full",
  "complete",
  "total",
  "whole",
  "entire",
  "all",
  "every",
  "each",
  "single",
  "double",
  "triple",
  "multiple",
  "many",
  "few",
  "some",
  "any",
  "no",
  "none",
  "zero",
  "one",
  "two",
  "three",
  "four",
  "five",
  "six",
  "seven",
  "eight",
  "nine",
  "ten",
  "hundred",
  "thousand",
  "million",
  "billion",
  "trillion",
] as const

// Domain validation schema
export const domainSchema = z.object({
  domain: z
    .string()
    .min(1, "Domain name is required")
    .max(253, "Domain name is too long")
    .regex(
      /^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/,
      "Invalid domain format",
    )
    .refine((domain) => {
      // Extract TLD (everything after the last dot)
      const parts = domain.split(".")
      if (parts.length < 2) return false

      const tld = parts[parts.length - 1].toLowerCase()
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      return VALID_TLDS.includes(tld as any)
    }, "Invalid or unsupported TLD")
    .refine((domain) => {
      // Additional checks
      const parts = domain.split(".")

      // Check each part length (max 63 characters per label)
      if (parts.some((part) => part.length > 63)) return false

      // Check for consecutive dots or starting/ending with dots
      if (domain.includes("..") || domain.startsWith(".") || domain.endsWith(".")) return false

      // Check for valid characters in each part
      return parts.every((part) => /^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?$/.test(part))
    }, "Invalid domain structure"),
})

export type DomainInput = z.infer<typeof domainSchema>

// Validation function
export function validateDomain(domain: string): { success: boolean; error?: string; data?: string } {
  try {
    const result = domainSchema.parse({ domain: domain.trim().toLowerCase() })
    return { success: true, data: result.domain }
  } catch (error) {
    if (error instanceof z.ZodError) {
      return { success: false, error: error.issues[0].message }
    }
    return { success: false, error: "Invalid domain format" }
  }
}
